# Generated by Django 4.1.13 on 2023-12-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPEN_API_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF_pathfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
